namespace Microsoft.Zune.PerfTrace;

public enum UICollectionEvent
{
	LibraryQueryIssued = 1,
	LibraryQueryResultsAvailable,
	LibraryQueryResultsVisible,
	MusicLibraryViewCommandInvoked,
	DeviceIconItemDropped,
	SearchQueryIssued,
	SearchQueryResultsAvailable,
	SearchQueryResultsVisible,
	MarketplaceQueriesIssued,
	MarketplaceQueriesResultsAvailable,
	MarketplaceQueriesResultsVisible,
	PlayRequestIssued,
	PlayRequestComplete,
	BulkEventsPushBegin,
	BulkEventsPushEnd,
	RecommendationQueriesIssued,
	RecommendationQueriesResultsAvailable,
	RecommendationQueriesResultsVisible,
	SocialQueriesIssued,
	SocialQueriesResultsAvailable,
	SocialQueriesResultsVisible,
	MixQueriesIssued,
	MixQueriesResultsAvailable,
	MixQueriesResultsVisible,
	QuickplayQueriesIssued,
	QuickplayQueriesResultsAvailable,
	QuickplayQueriesResultsVisible,
	DataProviderQueryBegin,
	DataProviderQueryComplete,
	QuickMixBegin,
	QuickMixUpdate,
	QuickMixComplete,
	MarketplaceSearchResultArtistClicked,
	SearchHintCollectionQueryArtistBegin,
	SearchHintCollectionQueryArtistComplete,
	SearchHintMarketplaceQueryPrefixBegin,
	SearchHintMarketplaceQueryPrefixComplete,
	SyncStatusVisible
}
