using System.Collections.Generic;

namespace ZuneUI;

internal class PhoneBrandingStringMap
{
	private static readonly PhoneBrandingStringMap _instance;

	protected bool _isBrandingEnabled;

	protected Dictionary<StringId, StringId> _stringMap = new Dictionary<StringId, StringId>();

	public static PhoneBrandingStringMap Instance => _instance;

	public bool BrandingEnabled
	{
		get
		{
			return _isBrandingEnabled;
		}
		set
		{
			if (_isBrandingEnabled != value)
			{
				_isBrandingEnabled = value;
			}
		}
	}

	protected PhoneBrandingStringMap()
	{
	}

	static PhoneBrandingStringMap()
	{
		_instance = new PhoneBrandingStringMap();
		_instance.Initialize();
	}

	public StringId TryGetMappedStringId(StringId stringId)
	{
		if (_stringMap.TryGetValue(stringId, out var value))
		{
			stringId = value;
		}
		return stringId;
	}

	public virtual void Initialize()
	{
		_stringMap[StringId.IDS_FIRMWARE_CURRENT_VERSION] = StringId.IDS_PHONE_CURRENT_VERSION;
		_stringMap[StringId.IDS_LIBRARY_QUESTION_N_ITEMS] = StringId.IDS_PHONE_LIBRARY_QUESTION_N_ITEMS;
		_stringMap[StringId.IDS_FIRMWARE_UPDATE_WARNING] = StringId.IDS_PHONE_FIRMWARE_UPDATE_WARNING;
		_stringMap[StringId.IDS_FIRMWARE_INSTALLING] = StringId.IDS_PHONE_FIRMWARE_INSTALLING;
		_stringMap[StringId.IDS_FIRMWARE_UPDATE_UNAVAILABLE] = StringId.IDS_PHONE_FIRMWARE_UPDATE_UNAVAILABLE;
		_stringMap[StringId.IDS_ASSOCIATE_ZUNE_OFFER_LOGGEDOUT] = StringId.IDS_PHONE_ASSOCIATE_ZUNE_OFFER_LOGGEDOUT;
		_stringMap[StringId.IDS_ASSOCIATE_ZUNE_OFFER_LOGGEDIN] = StringId.IDS_PHONE_ASSOCIATE_ZUNE_OFFER_LOGGEDIN;
		_stringMap[StringId.IDS_ASSOCIATE_ZUNE_OFFER_LOGGEDIN_YES] = StringId.IDS_PHONE_ASSOCIATE_ZUNE_OFFER_LOGGEDIN_YES;
		_stringMap[StringId.IDS_ASSOCIATED_ZUNE] = StringId.IDS_PHONE_ASSOCIATED_ZUNE;
		_stringMap[StringId.IDS_DELETE_DEVICE_BUTTON] = StringId.IDS_PHONE_DELETE_DEVICE_BUTTON;
		_stringMap[StringId.IDS_FORMAT_IN_PROGRESS] = StringId.IDS_PHONE_FORMAT_IN_PROGRESS;
		_stringMap[StringId.IDS_WIRELESS_SYNC_TEST_FAILED] = StringId.IDS_PHONE_WIRELESS_SYNC_TEST_FAILED;
		_stringMap[StringId.IDS_FORMAT_DIALOG_TEXT] = StringId.IDS_PHONE_FORMAT_DIALOG_TEXT;
		_stringMap[StringId.IDS_WIRELESS_SUGG_MAC_FILTERING] = StringId.IDS_PHONE_WIRELESS_SUGG_MAC_FILTERING;
		_stringMap[StringId.IDS_FIRMWARE_NEW_VERSION_OPTIONAL] = StringId.IDS_PHONE_FIRMWARE_NEW_VERSION_OPTIONAL;
		_stringMap[StringId.IDS_WIRELESS_ALREADY_CONFIGURED] = StringId.IDS_PHONE_WIRELESS_ALREADY_CONFIGURED;
		_stringMap[StringId.IDS_WIRELESS_DEVICE_BUSY] = StringId.IDS_PHONE_WIRELESS_DEVICE_BUSY;
		_stringMap[StringId.IDS_EULA_DIALOG_TITLE] = StringId.IDS_PHONE_EULA_DIALOG_TITLE;
		_stringMap[StringId.IDS_EULA_DIALOG_TITLE_REQUIRED] = StringId.IDS_PHONE_EULA_DIALOG_TITLE_REQUIRED;
		_stringMap[StringId.IDS_FIRMWARE_NEW_VERSION_REQUIRED] = StringId.IDS_PHONE_FIRMWARE_NEW_VERSION;
		_stringMap[StringId.IDS_EULA_DIALOG_TEXTAREA_TITLE] = StringId.IDS_PHONE_EULA_DIALOG_TEXTAREA_TITLE;
		_stringMap[StringId.IDS_FIRMWARE_UPDATE_AVAILABLE_TITLE] = StringId.IDS_PHONE_UPDATE_AVAILABLE_TITLE;
		_stringMap[StringId.IDS_SPACE_RESERVATION_DESCRIPTION] = StringId.IDS_PHONE_SPACE_RESERVATION_DESCRIPTION;
		_stringMap[StringId.IDS_SPACE_RESERVATION_DESCRIPTION_NO_FEATURES] = StringId.IDS_PHONE_SPACE_RESERVATION_DESCRIPTION_NO_MARKETPLACE;
		_stringMap[StringId.IDS_SPACE_RESERVATION_DESCRIPTION_NO_MARKETPLACE] = StringId.IDS_PHONE_SPACE_RESERVATION_DESCRIPTION_NO_MARKETPLACE;
		_stringMap[StringId.IDS_SPACE_RESERVATION_DESCRIPTION_NO_SOCIAL] = StringId.IDS_PHONE_SPACE_RESERVATION_DESCRIPTION;
		_stringMap[StringId.IDS_FIRMWARE_UPDATE_SUCCESS_NOTICE] = StringId.IDS_DEVICE_RESTORE_MAY_DISCONNECT;
		_stringMap[StringId.IDS_FIRMWARE_UPDATE_SUCCESS] = StringId.IDS_PHONE_UPDATE_SUCCESS;
		_stringMap[StringId.IDS_MUSIC_DEVICE_EMPTY] = StringId.IDS_PHONE_MUSIC_DEVICE_EMPTY;
		_stringMap[StringId.IDS_VIDEO_DEVICE_EMPTY] = StringId.IDS_PHONE_VIDEO_DEVICE_EMPTY;
		_stringMap[StringId.IDS_PHOTO_DEVICE_EMPTY] = StringId.IDS_PHONE_PHOTO_DEVICE_EMPTY;
		_stringMap[StringId.IDS_PLAYLIST_DEVICE_EMPTY_TITLE] = StringId.IDS_PHONE_PLAYLIST_DEVICE_EMPTY_TITLE;
		_stringMap[StringId.IDS_FIRMWARE_TRANSFERRING] = StringId.IDS_PHONE_FIRMWARE_TRANSFERRING;
		_stringMap[StringId.IDS_FIRMWARE_VERSION_PRE_TEXT] = StringId.IDS_PHONE_FIRMWARE_VERSION_PRE_TEXT;
		_stringMap[StringId.IDS_ASSOCIATE_YOUR_ZUNE_DESCRIPTION2] = StringId.IDS_PHONE_ASSOCIATE_YOUR_ZUNE_DESCRIPTION2;
		_stringMap[StringId.IDS_NO_SYNC_OPTIONS_INFO] = StringId.IDS_PHONE_NO_SYNC_OPTIONS_INFO;
		_stringMap[StringId.IDS_TRANSCODE_VIDEO_PLAYBACK_OPTION] = StringId.IDS_PHONE_TRANSCODE_VIDEO_PLAYBACK_OPTION;
		_stringMap[StringId.IDS_REMOVE_SINGLE_SYNC_GROUP_DIALOG_TEXT] = StringId.IDS_PHONE_REMOVE_SINGLE_SYNC_GROUP_DIALOG_TEXT;
		_stringMap[StringId.IDS_REMOVE_MULTIPLE_SYNC_GROUP_DIALOG_TEXT] = StringId.IDS_PHONE_REMOVE_MULTIPLE_SYNC_GROUP_DIALOG_TEXT;
		_stringMap[StringId.IDS_REMOVE_SYNC_ALL_GROUP_DIALOG_TEXT] = StringId.IDS_PHONE_REMOVE_SYNC_ALL_GROUP_DIALOG_TEXT;
		_stringMap[StringId.IDS_FIRMWARE_UPDATE_SUCCESS] = StringId.IDS_PHONE_FIRMWARE_UPDATE_SUCCESS;
		_stringMap[StringId.IDS_ENABLE_ZUNE_MARKETPLACE_TEXT] = StringId.IDS_PHONE_ENABLE_ZUNE_MARKETPLACE_TEXT;
		_stringMap[StringId.IDS_ENABLE_ZUNE_MARKETPLACE_OPTION] = StringId.IDS_PHONE_ENABLE_ZUNE_MARKETPLACE_OPTION;
		_stringMap[StringId.IDS_PICK_A_NAME_HEADER] = StringId.IDS_PHONE_PICK_A_NAME_HEADER;
		_stringMap[StringId.IDS_DISABLE_MARKETPLACE_BUTTON] = StringId.IDS_PHONE_DISABLE_MARKETPLACE_BUTTON;
		_stringMap[StringId.IDS_FIRMWARE_UPDATE_ERROR_NOTICE2] = StringId.IDS_PHONE_FIRMWARE_UPDATE_ERROR_NOTICE2;
		_stringMap[StringId.IDS_FIRMWARE_NEW_VERSION_REQUIRED] = StringId.IDS_PHONE_FIRMWARE_NEW_VERSION_REQUIRED;
		_stringMap[StringId.IDS_FIRMWARE_NOTICE] = StringId.IDS_PHONE_FIRMWARE_NOTICE;
		_stringMap[StringId.IDS_FIRMWARE_UPDATE_SUCCESS_NOTICE] = StringId.IDS_PHONE_FIRMWARE_UPDATE_SUCCESS_NOTICE;
		_stringMap[StringId.IDS_SYNC_CHAN_FRIEND_DISABLED_EXPLANATION] = StringId.IDS_PHONE_SYNC_CHAN_FRIEND_DISABLED_EXPLANATION;
		_stringMap[StringId.IDS_FIRMWARE_MANDATE] = StringId.IDS_PHONE_FIRMWARE_MANDATE;
		_stringMap[StringId.IDS_ZUNE_MARKETPLACE_LINKEDTO] = StringId.IDS_PHONE_ZUNE_MARKETPLACE_LINKEDTO;
		_stringMap[StringId.IDS_ENABLE_ZUNE_SOCIAL_TEXT_NO_MP] = StringId.IDS_PHONE_ENABLE_ZUNE_SOCIAL_TEXT_NO_MP;
		_stringMap[StringId.IDS_FRIENDS_EMPTY_DEVICE_HEADER] = StringId.IDS_PHONE_FRIENDS_EMPTY_DEVICE_HEADER;
		_stringMap[StringId.IDS_RENT_TARGET_DEVICE] = StringId.IDS_PHONE_RENT_TARGET_DEVICE;
		_stringMap[StringId.IDS_PODCAST_EMPTY_DEVICE_TITLE] = StringId.IDS_PHONE_PODCAST_EMPTY_DEVICE_TITLE;
		_stringMap[StringId.IDS_CHANNELS_EMPTY_DEVICE_TITLE] = StringId.IDS_PHONE_CHANNELS_EMPTY_DEVICE_TITLE;
		_stringMap[StringId.IDS_DEVICE_UP_TO_DATE] = StringId.IDS_PHONE_DEVICE_UP_TO_DATE;
		_stringMap[StringId.IDS_DEVICE_NAME_EMPTY] = StringId.IDS_PHONE_DEVICE_NAME_EMPTY;
		_stringMap[StringId.IDS_ITEMS_SYNCED_DESCRIPTION] = StringId.IDS_PHONE_ITEMS_SYNCED_DESCRIPTION;
		_stringMap[StringId.IDS_ITEMS_REMAINING_DESCRIPTION] = StringId.IDS_PHONE_ITEMS_REMAINING_DESCRIPTION;
		_stringMap[StringId.IDS_DEVICE_SETTINGS_NAME] = StringId.IDS_PHONE_DEVICE_SETTINGS_NAME;
		_stringMap[StringId.IDS_ALL_SYNCED_ITEMS] = StringId.IDS_PHONE_ALL_SYNCED_ITEMS;
		_stringMap[StringId.IDS_COMPUTER_ICON_DROP_TARGET_TOOLTIP] = StringId.IDS_PHONE_COMPUTER_ICON_DROP_TARGET_TOOLTIP;
		_stringMap[StringId.IDS_ALL_PICTURE_ITEMS] = StringId.IDS_PHONE_ALL_PICTURE_ITEMS;
		_stringMap[StringId.IDS_ALL_PODCAST_ITEMS] = StringId.IDS_PHONE_ALL_PODCAST_ITEMS;
		_stringMap[StringId.IDS_DEVICE_HUNG] = StringId.IDS_PHONE_DEVICE_HUNG;
		_stringMap[StringId.IDS_OUT_OF_SPACE_GAS_GAUGE_FORMAT] = StringId.IDS_PHONE_OUT_OF_SPACE_GAS_GAUGE_FORMAT;
		_stringMap[StringId.IDS_GUEST_OUT_OF_SPACE_MESSAGE] = StringId.IDS_PHONE_GUEST_OUT_OF_SPACE_MESSAGE;
		_stringMap[StringId.IDS_DEVICE_STATUS_SOCIAL_DESC_NO_ASSOC] = StringId.IDS_PHONE_DEVICE_STATUS_SOCIAL_DESC_NO_ASSOC;
		_stringMap[StringId.IDS_NOT_OUT_OF_SPACE_GAS_GAUGE_FORMAT] = StringId.IDS_PHONE_NOT_OUT_OF_SPACE_GAS_GAUGE_FORMAT;
		_stringMap[StringId.IDS_DEVICE_STATUS_SOCIAL_DESC_ASSOC] = StringId.IDS_PHONE_DEVICE_STATUS_SOCIAL_DESC_ASSOC;
		_stringMap[StringId.IDS_DEVICE_SUMMARY_DEVICE_UPDATE_TITLE] = StringId.IDS_PHONE_DEVICE_SUMMARY_DEVICE_UPDATE_TITLE;
		_stringMap[StringId.IDS_DEVICE_RENTAL_GUEST_NOT_SUPPORTED] = StringId.IDS_PHONE_DEVICE_RENTAL_GUEST_NOT_SUPPORTED;
		_stringMap[StringId.IDS_HOW_TO_SYNC_TO_ZUNE_DEVICES] = StringId.IDS_HOW_TO_SYNC_TO_PHONE_DEVICES;
		_stringMap[StringId.IDS_DEVICE_PIVOT] = StringId.IDS_PHONE_PIVOT;
		_stringMap[StringId.IDS_ITEMS_SYNCED_TITLE] = StringId.IDS_PHONE_ITEMS_SYNCED_TITLE;
		_stringMap[StringId.IDS_ITEMS_REMAINING_TITLE] = StringId.IDS_PHONE_ITEMS_REMAINING_TITLE;
		_stringMap[StringId.IDS_ITEMS_REMOVED_TITLE] = StringId.IDS_PHONE_ITEMS_REMOVED_TITLE;
		_stringMap[StringId.IDS_ITEMS_FAILED_TITLE] = StringId.IDS_PHONE_ITEMS_FAILED_TITLE;
		_stringMap[StringId.IDS_NAME_ZUNE_HEADER] = StringId.IDS_NAME_PHONE_HEADER;
		_stringMap[StringId.IDS_DEVICE_SUMMARY_AVAILABLE_FW_VERSION_HEADER] = StringId.IDS_DEVICE_SUMMARY_AVAILABLE_UPDATE_HEADER;
	}
}
